version: "3"

services:
  server:
    build:
      context: ./servidor
      dockerfile: Dockerfile
    command:
      python3 /cliente/client.py
    image: ubuntu
    ports:
      - "5000:5000"
    volumes:
      - .:/servidor


  client:
    depends_on:
      - "server"
    build:
      context: ./cliente
      dockerfile: Dockerfile
    command:
      python3 /servidor/server.py
    image: ubuntu
    ports:
      - "5000:5000"
    volumes:
      - .:/cliente
