version: "3"

services:
  server:
    build: servidor/
    command: python3 servidor/server.py
    ports:
      - "5000:5000"
    volumes:
      - .:/servidor


  client:
    depends_on:
      - "server"
    build: cliente/
    command:
      python3 cliente/client.py
    volumes:
      - .:/cliente
